name: KunnertandTierney
favicon: null
layout_spectrum: 0.6651840377599001
typography_spectrum: 0.010457019554451108
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.17981376172974706
  lightness: 0.6631949292495847
  saturation: 0.5712342483457178
  rhythmicContrast: 0.23465464101172984
purpose: []
